"""
NTP-SCTAP Database Schema Definitions.

All CREATE TABLE statements live here as plain SQL strings. This keeps
the schema declarative and version-controllable. The DatabaseManager
executes these statements during ``initialize()``.

Design notes:
  - Every table has an explicit TEXT primary key (UUID-based) rather
    than INTEGER AUTOINCREMENT so that IDs are generated by application
    code, making replication and testing deterministic.
  - Timestamps are stored as ISO-8601 TEXT for portability across
    SQLite and potential future migrations.
  - Foreign keys are declared but enforcement depends on
    ``PRAGMA foreign_keys = ON`` (set in the manager).
"""

# ── Packets ──────────────────────────────────────────────────────────
CREATE_PACKETS_TABLE = """
CREATE TABLE IF NOT EXISTS packets (
    id              TEXT PRIMARY KEY,
    session_id      TEXT,
    direction       TEXT NOT NULL CHECK(direction IN ('sent', 'received')),
    source_host     TEXT NOT NULL,
    source_port     INTEGER NOT NULL,
    dest_host       TEXT NOT NULL,
    dest_port       INTEGER NOT NULL,
    protocol        TEXT NOT NULL DEFAULT 'NTP',
    packet_type     TEXT,
    packet_size     INTEGER NOT NULL,
    raw_data        BLOB,
    payload_status  TEXT DEFAULT 'none',
    encryption_status TEXT DEFAULT 'none',
    validation      TEXT DEFAULT 'pending',
    metadata_json   TEXT DEFAULT '{}',
    created_at      TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id)
);
"""

# ── Messages ─────────────────────────────────────────────────────────
CREATE_MESSAGES_TABLE = """
CREATE TABLE IF NOT EXISTS messages (
    id              TEXT PRIMARY KEY,
    session_id      TEXT,
    packet_id       TEXT,
    direction       TEXT NOT NULL CHECK(direction IN ('sent', 'received')),
    plaintext       TEXT,
    ciphertext      BLOB,
    encryption_algo TEXT NOT NULL DEFAULT 'AES-256-GCM',
    status          TEXT NOT NULL DEFAULT 'pending',
    created_at      TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    FOREIGN KEY (packet_id) REFERENCES packets(id)
);
"""

# ── Sessions ─────────────────────────────────────────────────────────
CREATE_SESSIONS_TABLE = """
CREATE TABLE IF NOT EXISTS sessions (
    id              TEXT PRIMARY KEY,
    status          TEXT NOT NULL DEFAULT 'active',
    sender_host     TEXT,
    receiver_host   TEXT,
    packets_sent    INTEGER DEFAULT 0,
    packets_received INTEGER DEFAULT 0,
    started_at      TEXT NOT NULL,
    ended_at        TEXT,
    metadata_json   TEXT DEFAULT '{}'
);
"""

# ── Threats ──────────────────────────────────────────────────────────
CREATE_THREATS_TABLE = """
CREATE TABLE IF NOT EXISTS threats (
    id              TEXT PRIMARY KEY,
    packet_id       TEXT,
    session_id      TEXT,
    threat_level    TEXT NOT NULL DEFAULT 'low',
    confidence      REAL NOT NULL DEFAULT 0.0,
    alert_reason    TEXT NOT NULL,
    severity        TEXT NOT NULL DEFAULT 'info',
    recommendation  TEXT,
    details_json    TEXT DEFAULT '{}',
    detected_at     TEXT NOT NULL,
    FOREIGN KEY (packet_id) REFERENCES packets(id),
    FOREIGN KEY (session_id) REFERENCES sessions(id)
);
"""

# ── Analytics (time-series snapshots) ────────────────────────────────
CREATE_ANALYTICS_TABLE = """
CREATE TABLE IF NOT EXISTS analytics (
    id              TEXT PRIMARY KEY,
    metric_name     TEXT NOT NULL,
    metric_value    REAL NOT NULL,
    unit            TEXT DEFAULT '',
    recorded_at     TEXT NOT NULL
);
"""

# ── System Events ────────────────────────────────────────────────────
CREATE_EVENTS_TABLE = """
CREATE TABLE IF NOT EXISTS events (
    id              TEXT PRIMARY KEY,
    event_type      TEXT NOT NULL,
    severity        TEXT NOT NULL DEFAULT 'info',
    source          TEXT NOT NULL,
    message         TEXT NOT NULL,
    details_json    TEXT DEFAULT '{}',
    created_at      TEXT NOT NULL
);
"""

# ── Errors ───────────────────────────────────────────────────────────
CREATE_ERRORS_TABLE = """
CREATE TABLE IF NOT EXISTS errors (
    id              TEXT PRIMARY KEY,
    error_type      TEXT NOT NULL,
    module          TEXT NOT NULL,
    message         TEXT NOT NULL,
    traceback       TEXT,
    created_at      TEXT NOT NULL
);
"""

# ── System Logs ──────────────────────────────────────────────────────
CREATE_LOGS_TABLE = """
CREATE TABLE IF NOT EXISTS system_logs (
    id              TEXT PRIMARY KEY,
    level           TEXT NOT NULL,
    logger_name     TEXT NOT NULL,
    message         TEXT NOT NULL,
    created_at      TEXT NOT NULL
);
"""

# ── Configuration (runtime key-value store) ──────────────────────────
CREATE_CONFIG_TABLE = """
CREATE TABLE IF NOT EXISTS configuration (
    key             TEXT PRIMARY KEY,
    value           TEXT NOT NULL,
    description     TEXT DEFAULT '',
    updated_at      TEXT NOT NULL
);
"""

# ── Indexes ──────────────────────────────────────────────────────────
CREATE_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_packets_session ON packets(session_id);",
    "CREATE INDEX IF NOT EXISTS idx_packets_created ON packets(created_at);",
    "CREATE INDEX IF NOT EXISTS idx_packets_direction ON packets(direction);",
    "CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id);",
    "CREATE INDEX IF NOT EXISTS idx_threats_detected ON threats(detected_at);",
    "CREATE INDEX IF NOT EXISTS idx_threats_level ON threats(threat_level);",
    "CREATE INDEX IF NOT EXISTS idx_analytics_metric ON analytics(metric_name);",
    "CREATE INDEX IF NOT EXISTS idx_analytics_recorded ON analytics(recorded_at);",
    "CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);",
    "CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_at);",
    "CREATE INDEX IF NOT EXISTS idx_errors_created ON errors(created_at);",
    "CREATE INDEX IF NOT EXISTS idx_logs_created ON system_logs(created_at);",
]

# Ordered list for the manager to iterate.
ALL_TABLES = [
    CREATE_SESSIONS_TABLE,
    CREATE_PACKETS_TABLE,
    CREATE_MESSAGES_TABLE,
    CREATE_THREATS_TABLE,
    CREATE_ANALYTICS_TABLE,
    CREATE_EVENTS_TABLE,
    CREATE_ERRORS_TABLE,
    CREATE_LOGS_TABLE,
    CREATE_CONFIG_TABLE,
]
